services:
  backend:
    build: ./backend
    container_name: fivefasad-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - fivefasad-network

  php:
    image: php:8.2-fpm-alpine
    container_name: fivefasad-php
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/html
    environment:
      - MAILERSEND_API_TOKEN=mlsn.965f7a5c00daee38a4ceef2d3615326952c8a026ae82533d12872646fec3f160
      - MAILERSEND_FROM_EMAIL=noreply@5fasad.ru
      - MAILERSEND_FROM_NAME=Five Fasad
      - MAILERSEND_TO_EMAIL=parkhometsnikita@gmail.com
    networks:
      - fivefasad-network

  nginx:
    image: nginx:alpine
    container_name: fivefasad-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/var/www/html
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - php
    networks:
      - fivefasad-network

networks:
  fivefasad-network:
    driver: bridge